### ISSUE TITLE
Cache Directory

### ISSUE THREAD

**Issue by HDVinnie** [linslin/laravel-coffee-cache#1]
`Create a cache folder name coffeeCache in app/storage/. So you have this folder created: app/storage/coffeeCache.`

Is this right? There is no `app/storage/`. Do you mean `storage/app`? Or just `storage`?

[![Screen-Shot-2020-05-09-at-11-24-49-AM.png](https://i.postimg.cc/bY79Qc7X/Screen-Shot-2020-05-09-at-11-24-49-AM.png)](https://postimg.cc/s1JWr8fK)

**Comment by linslin** [comment]
Thanks for this hint. `storage/coffeeCache` is right. I already changed this in the readme!
