### ISSUE TITLE
Create subdirectory structure for the cache

### ISSUE THREAD

**Issue by andreasscherbaum** [linslin/laravel-coffee-cache#2]
The current implementation will drop all files into the cache directory, leading to a massive amount of files in one directory. Depending on the underlying filesystem, this will stop working at a certain point.
In any case this adds overhead, as the directory must be scanned with all entries.

Solution: add a subdirectory structure with 2-3 levels, and use the first characters of the filename for the subdirectory.

Example: http://www.squid-cache.org/Versions/v3/3.5/cfgman/cache_dir.html

**Comment by linslin** [comment]
Solved in 1.8.0
