### ISSUE TITLE
spaceLeftOnDevice() checks the root directory, not the storage path

### ISSUE THREAD

**Issue by andreasscherbaum** [linslin/laravel-coffee-cache#3]
The root directory ("/") is hardcoded into spaceLeftOnDevice(). This might check the wrong path for free space, as the cache directory might be a mounted RAM disk, or a device mounted from a SAN.

**Comment by andreasscherbaum** [comment]
Oh, and this checks for "/", which only works on Linux/Unix/Mac.

**Comment by linslin** [comment]
Fixed in 1.8.2
